41c41
< FROM node:${NODEJS_VERSION}-alpine AS web
---
> FROM debian:${OS_VERSION}-slim AS web
47c47,48
< ENV JELLYFIN_VERSION=${JELLYFIN_VERSION}
---
> ENV JELLYFIN_VERSION=${JELLYFIN_VERSION} \
>     DEBIAN_FRONTEND=noninteractive
49,63c50,52
< RUN apk add \
<     autoconf \
<     g++ \
<     make \
<     libpng-dev \
<     gifsicle \
<     alpine-sdk \
<     automake \
<     libtool \
<     gcc \
<     musl-dev \
<     nasm \
<     python3 \
<     git \
<  && git config --global --add safe.directory /jellyfin/jellyfin-web
---
> RUN apt-get update \
>     && apt-get install --yes --no-install-recommends --no-install-suggests build-essential git nodejs gifsicle libpng-dev libtool autoconf automake python3 \
>     && git config --global --add safe.directory /jellyfin/jellyfin-web
88c77,78
< ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
---
> ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
>     DEBIAN_FRONTEND=noninteractive
91,95c81,89
<  && apt-get install --no-install-recommends --no-install-suggests --yes \
<     curl \
<     ca-certificates \
<     libicu76 \
<  && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel ${DOTNET_VERSION} --install-dir /usr/local/bin
---
>     && apt-get install --no-install-recommends --no-install-suggests --yes curl ca-certificates libicu76 g++ \
>     && curl -Lo dotnet-runtime.tar.gz https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/dotnet-runtime-8.0.1-linux-riscv64.tar.gz \
>     && curl -Lo dotnet-sdk.tar.gz https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/dotnet-sdk-8.0.101-linux-riscv64.tar.gz \
>     && mkdir -p /opt/dotnet \
>     && tar -C /opt/dotnet -xf dotnet-runtime.tar.gz \
>     && tar -C /opt/dotnet -xf dotnet-sdk.tar.gz \
>     && ln -s /opt/dotnet/dotnet /usr/local/bin/dotnet \
>     && dotnet --version \
>     && rm -rf /var/cache/apt/archives* /var/lib/apt/lists/* dotnet-*.tar.gz
