18,19c18,19
< # Use Debian 12 w/ faster package updates: https://packages.debian.org/bookworm-backports/
< FROM python:3.11-slim-bookworm
---
> # Use Debian 12 w/ faster package updates: https://packages.debian.org/trixie-backports/
> FROM python:3.11-slim-trixie
109c109
<     && echo 'deb https://deb.debian.org/debian bookworm-backports main contrib non-free' >> /etc/apt/sources.list.d/backports.list \
---
>     && echo 'deb https://deb.debian.org/debian trixie-backports main contrib non-free' >> /etc/apt/sources.list.d/backports.list \
112c112
<     && apt-get install -qq -y -t bookworm-backports --no-install-recommends \
---
>     && apt-get install -qq -y -t trixie-backports --no-install-recommends \
126,127d125
<     && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_VERSION}.x nodistro main" >> /etc/apt/sources.list.d/nodejs.list \
<     && curl -fsSL "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key" | gpg --dearmor | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
129,130c127,128
<     && apt-get install -qq -y -t bookworm-backports --no-install-recommends \
<         nodejs libatomic1 python3-minimal \
---
>     && apt-get install -qq -y --no-install-recommends --no-install-suggests \
>         nodejs npm libatomic1 python3-minimal \
166c164
<     && apt-get install -qq -y -t bookworm-backports --no-install-recommends \
---
>     && apt-get install -qq -y -t trixie-backports --no-install-recommends \
194,196c192,198
<         apt-get install -qq -y -t bookworm-backports --no-install-recommends \
<             chromium fontconfig fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-symbola fonts-noto fonts-freefont-ttf \
<         && export CHROME_BINARY="$(which chromium)"; \
---
>         apt-get install -qq -y -t trixie-backports --no-install-recommends \
>             fontconfig fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst-one fonts-symbola fonts-noto fonts-freefont-ttf \
>         # Note: chromium package is not available on Debian Trixie for now, so we install chromium from unofficial source.
>         && wget -O chromium.deb https://github.com/riscv-forks/chromium-riscv/releases/download/146.0.7680.71/chromium-browser-stable_146.0.7680.71-1_riscv64.deb \
>         && apt-get install ./chromium.deb
>         && /usr/bin/chromium --version \
>         && export CHROME_BINARY=/usr/bin/chromium; \
230c232
<     && apt-get install -qq -y -t bookworm-backports --no-install-recommends \
---
>     && apt-get install -qq -y -t trixie-backports --no-install-recommends \
252c254
<     # && apt-get install -qq -y -t bookworm-backports --no-install-recommends \
---
>     # && apt-get install -qq -y -t trixie-backports --no-install-recommends \
