18,19c18,19
< # Use Debian 12 w/ faster package updates: https://packages.debian.org/bookworm-backports/
< FROM python:3.11-slim-bookworm
---
> # Use Debian 12 w/ faster package updates: https://packages.debian.org/trixie-backports/
> FROM python:3.11-slim-trixie
109c109
<     && echo 'deb https://deb.debian.org/debian bookworm-backports main contrib non-free' >> /etc/apt/sources.list.d/backports.list \
---
>     && echo 'deb https://deb.debian.org/debian trixie-backports main contrib non-free' >> /etc/apt/sources.list.d/backports.list \
112c112
<     && apt-get install -qq -y -t bookworm-backports --no-install-recommends \
---
>     && apt-get install -qq -y -t trixie-backports --no-install-recommends \
126,129c126,127
<     && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_VERSION}.x nodistro main" >> /etc/apt/sources.list.d/nodejs.list \
<     && curl -fsSL "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key" | gpg --dearmor | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
<     && apt-get update -qq \
<     && apt-get install -qq -y -t bookworm-backports --no-install-recommends \
---
>     apt-get update -qq \
>     && apt-get install -qq -y --no-install-recommends \
166c164
<     && apt-get install -qq -y -t bookworm-backports --no-install-recommends \
---
>     && apt-get install -qq -y -t trixie-backports --no-install-recommends \
194c192
<         apt-get install -qq -y -t bookworm-backports --no-install-recommends \
---
>         apt-get install -qq -y -t trixie-backports --no-install-recommends \
230c228
<     && apt-get install -qq -y -t bookworm-backports --no-install-recommends \
---
>     && apt-get install -qq -y -t trixie-backports --no-install-recommends \
252c250
<     # && apt-get install -qq -y -t bookworm-backports --no-install-recommends \
---
>     # && apt-get install -qq -y -t trixie-backports --no-install-recommends \
